source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.5', require: 'sinatra/base'
gem 'puma', '~> 2.0.1', group: :development
gem 'sequel', '~> 3.48.0'
gem 'pg', '~> 0.18.1'
gem 'geocoder', '~> 1.1.8'
gem 'rake', '~> 10.0.4'
gem 'haml'
gem 'sinatra-twitter-bootstrap'
gem 'compass-rails', '~> 1.0.3'
gem 'thin', '~> 1.6.2'
gem 'airbrake', '~> 3.1.12'
gem 'foreman', '~> 0.63.0'
gem 'dotenv', '~> 0.10.0'
gem 'rack-flash3'
gem 'sinatra-contrib', '~> 1.4.2'
gem 'capistrano', '~> 3.1.0'
