name             'whatsmydistrict'
maintainer       'OpenLexington'
maintainer_email 'info@openlexington.org'
license          'Apache 2.0'
description      'Installs/Configures whatsmydistrict'
long_description 'Installs/Configures whatsmydistrict'
version          '0.1.0'

depends 'annoyances', '= 1.0.0'
depends 'apt', '= 2.6.0'
depends 'build-essential', '= 2.0.2'
depends 'nginx', '= 2.7.4'
depends 'database', '= 2.2.0'
depends 'git', '= 4.0.2'
depends 'git_user', '= 0.3.0'
depends 'postgresql', '= 3.4.6'
depends 'imagemagick', '= 0.2.3'
depends 'git', '= 4.0.2'
depends 'sudo', '= 2.6.0'
depends 'tmux'
depends 'vim'
